### ISSUE TITLE
URL is invalid

### ISSUE THREAD

**Issue by Trevo1** [joelsjoyt/Animal-Classifier#1]
this：
Model trained by me if you want to test any images in the listed 10 classes https://drive.google.com/file/d/1kXXzu_biwAQRnRmw9PSq9qLrucD9wvDS/view?usp=sharing

**Comment by joelsjoyt** [comment]
It would have been deleted after I exceeded the G drive limit. You can use the data.zip to train the model via google colab, there is not much difference between my trained model and newly trained model. Sorry for the inconvenience.

**Comment by joelsjoyt** [comment]
Found the file here you go https://drive.google.com/file/d/11f9FlDNwXuz2djwdMk_gwCbWWzVk-OO4/view?usp=sharing

**Comment by Trevo1** [comment]
> Found the file here you go https://drive.google.com/file/d/11f9FlDNwXuz2djwdMk_gwCbWWzVk-OO4/view?usp=sharing

thanks ~

**Comment by joelsjoyt** [comment]
File is re-linked
